---
- name: Configure Docker
  hosts: node1
  gather_facts: true
  become: true

  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Add devopsadmin to docker group
      user:
        name: devopsadmin
        groups: docker
        append: yes

    - name: Change ownership of docker.sock
      file:
        path: /var/run/docker.sock
        owner: devopsadmin
        group: docker
        state: file
    - name: Run the image in detached mode
      shell: docker run -itd -p 8080:8080 ajay206/finance_app:latest
